//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cim.Manager.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cim.Manager.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   사고발생 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccidentEventList {
            get {
                return ResourceManager.GetString("AccidentEventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사고유형 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccidentTypeList {
            get {
                return ResourceManager.GetString("AccidentTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀파일이 생성되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Alert_CompletedExcelOutput {
            get {
                return ResourceManager.GetString("Alert_CompletedExcelOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성공적으로 삭제되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Alert_Delete_Result_Success {
            get {
                return ResourceManager.GetString("Alert_Delete_Result_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모듈 로딩에 실패하였습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Alert_ModuleLoadingFailed {
            get {
                return ResourceManager.GetString("Alert_ModuleLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   항목을 선택후 다시 시도하여 주십시요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Alert_NoSelection {
            get {
                return ResourceManager.GetString("Alert_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터가 유효하지 않습니다. 
        ///수정후 다시 시도하여 주십시요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Alert_NotValid {
            get {
                return ResourceManager.GetString("Alert_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   탐색하려는 주소가 올바르지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Alert_NotValidNavigationUrl {
            get {
                return ResourceManager.GetString("Alert_NotValidNavigationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장  실패하였습니다.
        ///확인 후 다시 시도해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Alert_Saving_Result_Failed {
            get {
                return ResourceManager.GetString("Alert_Saving_Result_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장완료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Alert_Saving_Result_Success {
            get {
                return ResourceManager.GetString("Alert_Saving_Result_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 최신버전입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlreadyUpToDate {
            get {
                return ResourceManager.GetString("AlreadyUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영상을 분석중입니다...
        ///잠시만 기다려 주십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AnalyzeScreen {
            get {
                return ResourceManager.GetString("AnalyzeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   카메라할당 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CameraAssignList {
            get {
                return ResourceManager.GetString("CameraAssignList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   카메라 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CameraList {
            get {
                return ResourceManager.GetString("CameraList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 확인 취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CancelCheckingMenu {
            get {
                return ResourceManager.GetString("CancelCheckingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업이 취소되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CancelOperation {
            get {
                return ResourceManager.GetString("CancelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   강화학습을 취소합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CancelReinforcementLearning {
            get {
                return ResourceManager.GetString("CancelReinforcementLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CancelUpdatingMenu {
            get {
                return ResourceManager.GetString("CancelUpdatingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %version% 버전으로 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChangesInVersion {
            get {
                return ResourceManager.GetString("ChangesInVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가됨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChangeStatus_Added {
            get {
                return ResourceManager.GetString("ChangeStatus_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제됨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChangeStatus_Deleted {
            get {
                return ResourceManager.GetString("ChangeStatus_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경됨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChangeStatus_Modified {
            get {
                return ResourceManager.GetString("ChangeStatus_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChangeStatus_Unchanged {
            get {
                return ResourceManager.GetString("ChangeStatus_Unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CheckForUpdatesMenu {
            get {
                return ResourceManager.GetString("CheckForUpdatesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 확인중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   강화학습을 완료하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompletedReinforcementLearning {
            get {
                return ResourceManager.GetString("CompletedReinforcementLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분석이 완료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompleteToAnalysis {
            get {
                return ResourceManager.GetString("CompleteToAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   구성완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeCompleted {
            get {
                return ResourceManager.GetString("ComposeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부분구성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Composing {
            get {
                return ResourceManager.GetString("Composing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 항목을 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Confirm_DeleteSelectedItem {
            get {
                return ResourceManager.GetString("Confirm_DeleteSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ConfirmClose {
            get {
                return ResourceManager.GetString("ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초기화 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ConfirmInitialize {
            get {
                return ResourceManager.GetString("ConfirmInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상세보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DetailView {
            get {
                return ResourceManager.GetString("DetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   활성화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Disabled_False {
            get {
                return ResourceManager.GetString("Disabled_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비활성화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Disabled_True {
            get {
                return ResourceManager.GetString("Disabled_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 다운로드중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다운로드 및 업데이트 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DownloadUpdateMenu {
            get {
                return ResourceManager.GetString("DownloadUpdateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중복되는 이름이 존재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DuplicateNameExists {
            get {
                return ResourceManager.GetString("DuplicateNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   건과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EA {
            get {
                return ResourceManager.GetString("EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에러과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 추출중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Extracting {
            get {
                return ResourceManager.GetString("Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 확인 실패.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailedToCheck {
            get {
                return ResourceManager.GetString("FailedToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 다운로드 실패.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailedToDownload {
            get {
                return ResourceManager.GetString("FailedToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 추출 실패.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailedToExtract {
            get {
                return ResourceManager.GetString("FailedToExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀저장이 취소되었거나. 실패하였습니다. 
        ///문제가 지속되면 관리자에 문의하십시요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailOrCancelToSaveExcel {
            get {
                return ResourceManager.GetString("FailOrCancelToSaveExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제가 실패하였습니다. 수정후 다시 시도하여 주십시요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailToDelete {
            get {
                return ResourceManager.GetString("FailToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가가 실패하였습니다. 수정후 다시 시도하여 주십시요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailToInsert {
            get {
                return ResourceManager.GetString("FailToInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인쇄가 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailToPrint {
            get {
                return ResourceManager.GetString("FailToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   처리가 실패하였습니다. 수정후 다시 시도하여 주십시요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailToProcess {
            get {
                return ResourceManager.GetString("FailToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 조회가 실패하였습니다. 
        ///문제가 지속되면 관리자에 문의하십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailToRead {
            get {
                return ResourceManager.GetString("FailToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비전서버 데이터 조회가 실패하였습니다. 
        ///문제가 지속되면 비전서버 관리자에 문의하십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailToRead2 {
            get {
                return ResourceManager.GetString("FailToRead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   강화학습을 실패하였습니다. 
        ///문제가 지속되면 관리자에 문의하십시요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailToReinforcementLearning {
            get {
                return ResourceManager.GetString("FailToReinforcementLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장이 실패하였습니다. 수정후 다시 시도하여 주십시요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailToSave {
            get {
                return ResourceManager.GetString("FailToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀저장이 실패하였습니다. 
        ///문제가 지속되면 관리자에 문의하십시요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailToSaveExcel {
            get {
                return ResourceManager.GetString("FailToSaveExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   숨기기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HideMenu {
            get {
                return ResourceManager.GetString("HideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 시작시 업데이트가 진행됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InstallOnNextStart {
            get {
                return ResourceManager.GetString("InstallOnNextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바로 업데이트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InstallUpdateMenu {
            get {
                return ResourceManager.GetString("InstallUpdateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이메일이 잘못되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ip주소가 잘못되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidIpAddress {
            get {
                return ResourceManager.GetString("InvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정이 잘못되었습니다.
        ///문제가 지속되면 관리자에 문의하십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidSettings {
            get {
                return ResourceManager.GetString("InvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   학습 가능과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Learningable {
            get {
                return ResourceManager.GetString("Learningable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   학습 데이터 부족과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LearningDataLack {
            get {
                return ResourceManager.GetString("LearningDataLack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   학습 최적과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LearningOptimum {
            get {
                return ResourceManager.GetString("LearningOptimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라이센스 확인에 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LicenseCheckFailed {
            get {
                return ResourceManager.GetString("LicenseCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라이센스 확인에 성공하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LicenseCheckSucceeded {
            get {
                return ResourceManager.GetString("LicenseCheckSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 로딩중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터를 불러오는중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비전서버
        ///데이터를 불러오는중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoadingData2 {
            get {
                return ResourceManager.GetString("LoadingData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주 영상과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainScreen {
            get {
                return ResourceManager.GetString("MainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 카메라가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoCameraSelected {
            get {
                return ResourceManager.GetString("NoCameraSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경사항이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoChanged {
            get {
                return ResourceManager.GetString("NoChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   구성없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoCompose {
            get {
                return ResourceManager.GetString("NoCompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 파일이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   카메라를 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotFoundCamera {
            get {
                return ResourceManager.GetString("NotFoundCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영상을 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NotFoundVideo {
            get {
                return ResourceManager.GetString("NotFoundVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   외과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   출력정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OutputInfo {
            get {
                return ResourceManager.GetString("OutputInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로고침과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Retreive {
            get {
                return ResourceManager.GetString("Retreive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동일한 영상이 이미 재생되고 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SameVideoIsAlreadyPlaying {
            get {
                return ResourceManager.GetString("SameVideoIsAlreadyPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영상분석서버 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ScreenAnalysisServerList {
            get {
                return ResourceManager.GetString("ScreenAnalysisServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   화면목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ScreenList {
            get {
                return ResourceManager.GetString("ScreenList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색 종료 시간이 시작 시간보다 빠릅니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SearchEndTimeIsEarlierThanStartTime {
            get {
                return ResourceManager.GetString("SearchEndTimeIsEarlierThanStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색 종료 시간이 파일 종료 시간보다 큽니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SearchEndTimeIsGreaterThanFileEndTime {
            get {
                return ResourceManager.GetString("SearchEndTimeIsGreaterThanFileEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색 시작 시간이 파일 시작 시간보다 빠릅니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SearchStartTimeIsEarlierThanFileStartTime {
            get {
                return ResourceManager.GetString("SearchStartTimeIsEarlierThanFileStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색 시작 시간이 파일 종료 시간보다 큽니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SearchStartTimeIsGreaterThanFileEndTime {
            get {
                return ResourceManager.GetString("SearchStartTimeIsGreaterThanFileEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소셜맵과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SocialMap {
            get {
                return ResourceManager.GetString("SocialMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   강화학습을 시작합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartReinforcementLearning {
            get {
                return ResourceManager.GetString("StartReinforcementLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 확인 중지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopChecking {
            get {
                return ResourceManager.GetString("StopChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 다운로드 중지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopDownloading {
            get {
                return ResourceManager.GetString("StopDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 추출 중지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopExtracting {
            get {
                return ResourceManager.GetString("StopExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장영상 추적 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StorageVideoTraceList {
            get {
                return ResourceManager.GetString("StorageVideoTraceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보조영상 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SubScreenList {
            get {
                return ResourceManager.GetString("SubScreenList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %version% 버전으로 업데이트 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추적상세과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TraceDetail {
            get {
                return ResourceManager.GetString("TraceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추적목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TraceList {
            get {
                return ResourceManager.GetString("TraceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추적모드가 이미 시작되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TraceModeHasAlreadyBegun {
            get {
                return ResourceManager.GetString("TraceModeHasAlreadyBegun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추적관제 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TraceMonitoringList {
            get {
                return ResourceManager.GetString("TraceMonitoringList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추적요청목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TraceRequestList {
            get {
                return ResourceManager.GetString("TraceRequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   나중에 다시시도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TryAgainLater {
            get {
                return ResourceManager.GetString("TryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재시도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TryAgainNow {
            get {
                return ResourceManager.GetString("TryAgainNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알수없는 에러가 발생하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnknownErrorOccurred {
            get {
                return ResourceManager.GetString("UnknownErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장되지 않은 내용들은 제거됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnsavedContentRemoved {
            get {
                return ResourceManager.GetString("UnsavedContentRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 준비가 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 설치 실패.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateNowButton {
            get {
                return ResourceManager.GetString("UpdateNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동영상과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %version% 버전으로 뷰 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ViewChangesMenu {
            get {
                return ResourceManager.GetString("ViewChangesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상세에러 보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ViewError {
            get {
                return ResourceManager.GetString("ViewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비전서버목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VisionServerList {
            get {
                return ResourceManager.GetString("VisionServerList", resourceCulture);
            }
        }
    }
}
